"""initial_schema

Revision ID: 674e8f596e01
Revises: 4cae4220fc21
Create Date: 2026-03-23 13:48:45.967071+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '001_initial'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'accounts', 'users', ['user_id'], ['id'], source_schema='finances', referent_schema='finances', ondelete='CASCADE')
    op.create_foreign_key(None, 'budgets', 'users', ['user_id'], ['id'], source_schema='finances', referent_schema='finances', ondelete='CASCADE')
    op.create_foreign_key(None, 'budgets', 'categories', ['category_id'], ['id'], source_schema='finances', referent_schema='finances', ondelete='CASCADE')
    op.create_foreign_key(None, 'categories', 'users', ['user_id'], ['id'], source_schema='finances', referent_schema='finances', ondelete='CASCADE')
    op.create_foreign_key(None, 'telegram_link_tokens', 'users', ['user_id'], ['id'], source_schema='finances', referent_schema='finances', ondelete='CASCADE')
    op.add_column('transactions', sa.Column('enriched_category', sa.String(length=100), nullable=True))
    op.add_column('transactions', sa.Column('enriched_subcategory', sa.String(length=100), nullable=True))
    op.add_column('transactions', sa.Column('enriched_type', sa.String(length=50), nullable=True))
    op.add_column('transactions', sa.Column('income_type', sa.String(length=50), nullable=True))
    op.add_column('transactions', sa.Column('expense_type', sa.String(length=50), nullable=True))
    op.add_column('transactions', sa.Column('exclude_from_metrics', sa.Boolean(), nullable=False))
    op.add_column('transactions', sa.Column('is_group_payment', sa.Boolean(), nullable=False))
    op.add_column('transactions', sa.Column('net_amount', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('transactions', sa.Column('linked_tx_id', sa.Integer(), nullable=True))
    op.add_column('transactions', sa.Column('enrichment_source', sa.String(length=20), nullable=True))
    op.add_column('transactions', sa.Column('enrichment_confidence', sa.Numeric(precision=3, scale=2), nullable=True))
    op.add_column('transactions', sa.Column('review_status', sa.String(length=20), nullable=False))
    op.add_column('transactions', sa.Column('user_rule_id', sa.Integer(), nullable=True))
    op.add_column('transactions', sa.Column('enriched_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('transactions', sa.Column('contact_ref', sa.String(length=24), nullable=True))
    op.alter_column('transactions', 'import_source',
               existing_type=sa.VARCHAR(length=20),
               server_default='manual',
               existing_nullable=False)
    op.create_index('idx_transactions_contact_ref', 'transactions', ['contact_ref'], unique=False, schema='finances')
    op.create_index('idx_transactions_review_status', 'transactions', ['review_status'], unique=False, schema='finances')
    op.create_index(op.f('ix_finances_transactions_contact_ref'), 'transactions', ['contact_ref'], unique=False, schema='finances')
    op.create_index(op.f('ix_finances_transactions_external_id'), 'transactions', ['external_id'], unique=True, schema='finances')
    op.create_index(op.f('ix_finances_transactions_id'), 'transactions', ['id'], unique=False, schema='finances')
    op.create_foreign_key(None, 'transactions', 'categories', ['category_id'], ['id'], source_schema='finances', referent_schema='finances', ondelete='SET NULL')
    op.create_foreign_key(None, 'transactions', 'accounts', ['account_id'], ['id'], source_schema='finances', referent_schema='finances', ondelete='CASCADE')
    op.create_foreign_key(None, 'transactions', 'transactions', ['linked_tx_id'], ['id'], source_schema='finances', referent_schema='finances')
    op.create_foreign_key(None, 'transactions', 'users', ['user_id'], ['id'], source_schema='finances', referent_schema='finances', ondelete='CASCADE')
    op.create_foreign_key(None, 'transactions', 'accounts', ['target_account_id'], ['id'], source_schema='finances', referent_schema='finances', ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transactions', schema='finances', type_='foreignkey')
    op.drop_constraint(None, 'transactions', schema='finances', type_='foreignkey')
    op.drop_constraint(None, 'transactions', schema='finances', type_='foreignkey')
    op.drop_constraint(None, 'transactions', schema='finances', type_='foreignkey')
    op.drop_constraint(None, 'transactions', schema='finances', type_='foreignkey')
    op.drop_index(op.f('ix_finances_transactions_id'), table_name='transactions', schema='finances')
    op.drop_index(op.f('ix_finances_transactions_external_id'), table_name='transactions', schema='finances')
    op.drop_index(op.f('ix_finances_transactions_contact_ref'), table_name='transactions', schema='finances')
    op.drop_index('idx_transactions_review_status', table_name='transactions', schema='finances')
    op.drop_index('idx_transactions_contact_ref', table_name='transactions', schema='finances')
    op.alter_column('transactions', 'import_source',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=False)
    op.drop_column('transactions', 'contact_ref')
    op.drop_column('transactions', 'enriched_at')
    op.drop_column('transactions', 'user_rule_id')
    op.drop_column('transactions', 'review_status')
    op.drop_column('transactions', 'enrichment_confidence')
    op.drop_column('transactions', 'enrichment_source')
    op.drop_column('transactions', 'linked_tx_id')
    op.drop_column('transactions', 'net_amount')
    op.drop_column('transactions', 'is_group_payment')
    op.drop_column('transactions', 'exclude_from_metrics')
    op.drop_column('transactions', 'expense_type')
    op.drop_column('transactions', 'income_type')
    op.drop_column('transactions', 'enriched_type')
    op.drop_column('transactions', 'enriched_subcategory')
    op.drop_column('transactions', 'enriched_category')
    op.drop_constraint(None, 'telegram_link_tokens', schema='finances', type_='foreignkey')
    op.drop_constraint(None, 'categories', schema='finances', type_='foreignkey')
    op.drop_constraint(None, 'budgets', schema='finances', type_='foreignkey')
    op.drop_constraint(None, 'budgets', schema='finances', type_='foreignkey')
    op.drop_constraint(None, 'accounts', schema='finances', type_='foreignkey')
    # ### end Alembic commands ###
