"""initial schema

Revision ID: 0ac212ee8ce1
Revises: 
Create Date: 2026-03-10 00:54:10.590722+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ac212ee8ce1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='finances'
    )
    op.create_index(op.f('ix_finances_users_email'), 'users', ['email'], unique=True, schema='finances')
    op.create_index(op.f('ix_finances_users_username'), 'users', ['username'], unique=True, schema='finances')
    op.create_table('accounts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('account_number', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('bank_name', sa.String(length=100), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='raw_operations'
    )
    op.create_table('finance_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_number', sa.String(length=50), nullable=False),
    sa.Column('date_msk', sa.Date(), nullable=False),
    sa.Column('time_msk', sa.Time(), nullable=False),
    sa.Column('auth_code', sa.String(length=50), nullable=True),
    sa.Column('category', sa.String(length=255), nullable=True),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('tx_type', sa.String(length=20), nullable=True),
    sa.Column('balance', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('date_operation', sa.Date(), nullable=True),
    sa.Column('merchant', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='raw_operations'
    )
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=True),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='raw_operations'
    )
    op.create_table('accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('account_type', sa.String(length=50), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('balance', sa.DECIMAL(precision=15, scale=2), nullable=False),
    sa.Column('bank_name', sa.String(length=100), nullable=True),
    sa.Column('account_number', sa.String(length=50), nullable=True),
    sa.Column('last_four_digits', sa.String(length=4), nullable=True),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('include_in_total', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("account_type IN ('card', 'bank_account', 'cash', 'investment', 'crypto', 'other')", name='check_account_type'),
    sa.CheckConstraint('balance >= 0', name='check_balance_positive'),
    sa.ForeignKeyConstraint(['user_id'], ['finances.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='finances'
    )
    op.create_index('idx_accounts_type', 'accounts', ['account_type'], unique=False, schema='finances')
    op.create_index('idx_accounts_user', 'accounts', ['user_id'], unique=False, schema='finances')
    op.create_index(op.f('ix_finances_accounts_id'), 'accounts', ['id'], unique=False, schema='finances')
    op.create_table('categories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True, comment='NULL for system categories'),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('category_type', sa.String(length=20), nullable=False, comment='income, expense, transfer'),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=False, comment='System category (cannot be deleted by user)'),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['finances.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='finances'
    )
    op.create_index(op.f('ix_finances_categories_user_id'), 'categories', ['user_id'], unique=False, schema='finances')
    op.create_table('budgets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True, comment='NULL for total budget'),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('period_type', sa.String(length=20), nullable=False, comment='daily, weekly, monthly, yearly'),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['finances.categories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['finances.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='finances'
    )
    op.create_index(op.f('ix_finances_budgets_category_id'), 'budgets', ['category_id'], unique=False, schema='finances')
    op.create_index(op.f('ix_finances_budgets_user_id'), 'budgets', ['user_id'], unique=False, schema='finances')
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('target_account_id', sa.Integer(), nullable=True),
    sa.Column('transaction_date', sa.Date(), nullable=False),
    sa.Column('amount', sa.DECIMAL(precision=15, scale=2), nullable=False),
    sa.Column('transaction_type', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('merchant', sa.String(length=255), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('tags', sa.String(length=500), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('receipt_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("transaction_type IN ('income', 'expense', 'transfer')", name='check_transaction_type'),
    sa.CheckConstraint('amount >= 0', name='check_amount_positive'),
    sa.ForeignKeyConstraint(['account_id'], ['finances.accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['category_id'], ['finances.categories.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['target_account_id'], ['finances.accounts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['finances.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_transactions_account', 'transactions', ['account_id'], unique=False)
    op.create_index('idx_transactions_category', 'transactions', ['category_id'], unique=False)
    op.create_index('idx_transactions_type', 'transactions', ['transaction_type'], unique=False)
    op.create_index('idx_transactions_user_date', 'transactions', ['user_id', 'transaction_date'], unique=False)
    op.create_index(op.f('ix_transactions_id'), 'transactions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_id'), table_name='transactions')
    op.drop_index('idx_transactions_user_date', table_name='transactions')
    op.drop_index('idx_transactions_type', table_name='transactions')
    op.drop_index('idx_transactions_category', table_name='transactions')
    op.drop_index('idx_transactions_account', table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_finances_budgets_user_id'), table_name='budgets', schema='finances')
    op.drop_index(op.f('ix_finances_budgets_category_id'), table_name='budgets', schema='finances')
    op.drop_table('budgets', schema='finances')
    op.drop_index(op.f('ix_finances_categories_user_id'), table_name='categories', schema='finances')
    op.drop_table('categories', schema='finances')
    op.drop_index(op.f('ix_finances_accounts_id'), table_name='accounts', schema='finances')
    op.drop_index('idx_accounts_user', table_name='accounts', schema='finances')
    op.drop_index('idx_accounts_type', table_name='accounts', schema='finances')
    op.drop_table('accounts', schema='finances')
    op.drop_table('users', schema='raw_operations')
    op.drop_table('finance_transactions', schema='raw_operations')
    op.drop_table('accounts', schema='raw_operations')
    op.drop_index(op.f('ix_finances_users_username'), table_name='users', schema='finances')
    op.drop_index(op.f('ix_finances_users_email'), table_name='users', schema='finances')
    op.drop_table('users', schema='finances')
    # ### end Alembic commands ###
