"""add_telegram_support

Revision ID: 2a61cedac9c7
Revises: 0ac212ee8ce1
Create Date: 2026-03-15 13:43:58.267974+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a61cedac9c7'
down_revision: Union[str, None] = '0ac212ee8ce1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('telegram_link_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['finances.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='finances'
    )
    op.create_index(op.f('ix_finances_telegram_link_tokens_token'), 'telegram_link_tokens', ['token'], unique=True, schema='finances')
    op.create_index(op.f('ix_finances_telegram_link_tokens_user_id'), 'telegram_link_tokens', ['user_id'], unique=False, schema='finances')
    op.drop_constraint('accounts_user_id_fkey', 'accounts', type_='foreignkey')
    op.create_foreign_key(None, 'accounts', 'users', ['user_id'], ['id'], source_schema='finances', referent_schema='finances', ondelete='CASCADE')
    op.drop_constraint('budgets_user_id_fkey', 'budgets', type_='foreignkey')
    op.drop_constraint('budgets_category_id_fkey', 'budgets', type_='foreignkey')
    op.create_foreign_key(None, 'budgets', 'categories', ['category_id'], ['id'], source_schema='finances', referent_schema='finances', ondelete='CASCADE')
    op.create_foreign_key(None, 'budgets', 'users', ['user_id'], ['id'], source_schema='finances', referent_schema='finances', ondelete='CASCADE')
    op.drop_constraint('categories_user_id_fkey', 'categories', type_='foreignkey')
    op.create_foreign_key(None, 'categories', 'users', ['user_id'], ['id'], source_schema='finances', referent_schema='finances', ondelete='CASCADE')
    op.add_column('transactions', sa.Column('external_id', sa.String(length=100), nullable=True))
    op.add_column('transactions', sa.Column('import_source', sa.String(length=20), nullable=False))
    op.create_index(op.f('ix_transactions_external_id'), 'transactions', ['external_id'], unique=True)
    op.drop_constraint('transactions_target_account_id_fkey', 'transactions', type_='foreignkey')
    op.drop_constraint('transactions_category_id_fkey', 'transactions', type_='foreignkey')
    op.drop_constraint('transactions_account_id_fkey', 'transactions', type_='foreignkey')
    op.drop_constraint('transactions_user_id_fkey', 'transactions', type_='foreignkey')
    op.create_foreign_key(None, 'transactions', 'categories', ['category_id'], ['id'], referent_schema='finances', ondelete='SET NULL')
    op.create_foreign_key(None, 'transactions', 'users', ['user_id'], ['id'], referent_schema='finances', ondelete='CASCADE')
    op.create_foreign_key(None, 'transactions', 'accounts', ['target_account_id'], ['id'], referent_schema='finances', ondelete='SET NULL')
    op.create_foreign_key(None, 'transactions', 'accounts', ['account_id'], ['id'], referent_schema='finances', ondelete='CASCADE')
    op.add_column('users', sa.Column('telegram_id', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('telegram_username', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_finances_users_telegram_id'), 'users', ['telegram_id'], unique=True, schema='finances')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_finances_users_telegram_id'), table_name='users', schema='finances')
    op.drop_column('users', 'telegram_username')
    op.drop_column('users', 'telegram_id')
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.create_foreign_key('transactions_user_id_fkey', 'transactions', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('transactions_account_id_fkey', 'transactions', 'accounts', ['account_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('transactions_category_id_fkey', 'transactions', 'categories', ['category_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('transactions_target_account_id_fkey', 'transactions', 'accounts', ['target_account_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_transactions_external_id'), table_name='transactions')
    op.drop_column('transactions', 'import_source')
    op.drop_column('transactions', 'external_id')
    op.drop_constraint(None, 'categories', schema='finances', type_='foreignkey')
    op.create_foreign_key('categories_user_id_fkey', 'categories', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'budgets', schema='finances', type_='foreignkey')
    op.drop_constraint(None, 'budgets', schema='finances', type_='foreignkey')
    op.create_foreign_key('budgets_category_id_fkey', 'budgets', 'categories', ['category_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('budgets_user_id_fkey', 'budgets', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'accounts', schema='finances', type_='foreignkey')
    op.create_foreign_key('accounts_user_id_fkey', 'accounts', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_finances_telegram_link_tokens_user_id'), table_name='telegram_link_tokens', schema='finances')
    op.drop_index(op.f('ix_finances_telegram_link_tokens_token'), table_name='telegram_link_tokens', schema='finances')
    op.drop_table('telegram_link_tokens', schema='finances')
    # ### end Alembic commands ###
