"""add streak to habits

Revision ID: 3e9329094e83
Revises: 8aae31dde3c6
Create Date: 2026-03-26 20:43:46.147532+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e9329094e83'
down_revision: Union[str, None] = '8aae31dde3c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'accounts', 'users', ['user_id'], ['id'], source_schema='finances', referent_schema='finances', ondelete='CASCADE')
    op.create_foreign_key(None, 'budgets', 'users', ['user_id'], ['id'], source_schema='finances', referent_schema='finances', ondelete='CASCADE')
    op.create_foreign_key(None, 'budgets', 'categories', ['category_id'], ['id'], source_schema='finances', referent_schema='finances', ondelete='CASCADE')
    op.create_foreign_key(None, 'categories', 'users', ['user_id'], ['id'], source_schema='finances', referent_schema='finances', ondelete='CASCADE')
    op.create_foreign_key(None, 'habit_logs', 'habits', ['habit_id'], ['id'], source_schema='finances', referent_schema='finances', ondelete='CASCADE')
    op.add_column('habits', sa.Column('current_streak', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'habits', 'users', ['user_id'], ['id'], source_schema='finances', referent_schema='finances', ondelete='CASCADE')
    op.create_foreign_key(None, 'telegram_link_tokens', 'users', ['user_id'], ['id'], source_schema='finances', referent_schema='finances', ondelete='CASCADE')
    op.create_foreign_key(None, 'transactions', 'accounts', ['account_id'], ['id'], source_schema='finances', referent_schema='finances', ondelete='CASCADE')
    op.create_foreign_key(None, 'transactions', 'users', ['user_id'], ['id'], source_schema='finances', referent_schema='finances', ondelete='CASCADE')
    op.create_foreign_key(None, 'transactions', 'accounts', ['target_account_id'], ['id'], source_schema='finances', referent_schema='finances', ondelete='SET NULL')
    op.create_foreign_key(None, 'transactions', 'categories', ['category_id'], ['id'], source_schema='finances', referent_schema='finances', ondelete='SET NULL')
    op.create_foreign_key(None, 'transactions', 'transactions', ['linked_tx_id'], ['id'], source_schema='finances', referent_schema='finances')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transactions', schema='finances', type_='foreignkey')
    op.drop_constraint(None, 'transactions', schema='finances', type_='foreignkey')
    op.drop_constraint(None, 'transactions', schema='finances', type_='foreignkey')
    op.drop_constraint(None, 'transactions', schema='finances', type_='foreignkey')
    op.drop_constraint(None, 'transactions', schema='finances', type_='foreignkey')
    op.drop_constraint(None, 'telegram_link_tokens', schema='finances', type_='foreignkey')
    op.drop_constraint(None, 'habits', schema='finances', type_='foreignkey')
    op.drop_column('habits', 'current_streak')
    op.drop_constraint(None, 'habit_logs', schema='finances', type_='foreignkey')
    op.drop_constraint(None, 'categories', schema='finances', type_='foreignkey')
    op.drop_constraint(None, 'budgets', schema='finances', type_='foreignkey')
    op.drop_constraint(None, 'budgets', schema='finances', type_='foreignkey')
    op.drop_constraint(None, 'accounts', schema='finances', type_='foreignkey')
    # ### end Alembic commands ###
