"""add_external_id_import_source_to_transactions

Revision ID: 4cae4220fc21
Revises: 5f93d75f9bcf
Create Date: 2026-03-18 14:28:21.049996+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4cae4220fc21'
down_revision: Union[str, None] = '5f93d75f9bcf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'accounts', 'users', ['user_id'], ['id'], source_schema='finances', referent_schema='finances', ondelete='CASCADE')
    op.create_foreign_key(None, 'budgets', 'categories', ['category_id'], ['id'], source_schema='finances', referent_schema='finances', ondelete='CASCADE')
    op.create_foreign_key(None, 'budgets', 'users', ['user_id'], ['id'], source_schema='finances', referent_schema='finances', ondelete='CASCADE')
    op.create_foreign_key(None, 'categories', 'users', ['user_id'], ['id'], source_schema='finances', referent_schema='finances', ondelete='CASCADE')
    op.create_foreign_key(None, 'telegram_link_tokens', 'users', ['user_id'], ['id'], source_schema='finances', referent_schema='finances', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'telegram_link_tokens', schema='finances', type_='foreignkey')
    op.drop_constraint(None, 'categories', schema='finances', type_='foreignkey')
    op.drop_constraint(None, 'budgets', schema='finances', type_='foreignkey')
    op.drop_constraint(None, 'budgets', schema='finances', type_='foreignkey')
    op.drop_constraint(None, 'accounts', schema='finances', type_='foreignkey')
    # ### end Alembic commands ###
