"""change_telegram_id_to_bigint

Revision ID: 5f93d75f9bcf
Revises: 2a61cedac9c7
Create Date: 2026-03-18 12:24:35.187166+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5f93d75f9bcf'
down_revision: Union[str, None] = '2a61cedac9c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('telegram_upload_log', schema='bot')
    op.drop_index('ix_bot_ft_date_msk', table_name='finance_transactions', schema='bot')
    op.drop_index('ix_bot_ft_import_status', table_name='finance_transactions', schema='bot', postgresql_where="((import_status)::text = 'pending'::text)")
    op.drop_index('ix_bot_ft_telegram_id', table_name='finance_transactions', schema='bot')
    op.drop_index('ix_bot_ft_telegram_id_status', table_name='finance_transactions', schema='bot', postgresql_where="((import_status)::text = 'pending'::text)")
    op.drop_table('finance_transactions', schema='bot')
    op.drop_table('telegram_user_state', schema='bot')
    op.drop_constraint('accounts_user_id_fkey', 'accounts', type_='foreignkey')
    op.create_foreign_key(None, 'accounts', 'users', ['user_id'], ['id'], source_schema='finances', referent_schema='finances', ondelete='CASCADE')
    op.drop_constraint('budgets_category_id_fkey', 'budgets', type_='foreignkey')
    op.drop_constraint('budgets_user_id_fkey', 'budgets', type_='foreignkey')
    op.create_foreign_key(None, 'budgets', 'users', ['user_id'], ['id'], source_schema='finances', referent_schema='finances', ondelete='CASCADE')
    op.create_foreign_key(None, 'budgets', 'categories', ['category_id'], ['id'], source_schema='finances', referent_schema='finances', ondelete='CASCADE')
    op.drop_constraint('categories_user_id_fkey', 'categories', type_='foreignkey')
    op.create_foreign_key(None, 'categories', 'users', ['user_id'], ['id'], source_schema='finances', referent_schema='finances', ondelete='CASCADE')
    op.drop_constraint('telegram_link_tokens_user_id_fkey', 'telegram_link_tokens', type_='foreignkey')
    op.create_foreign_key(None, 'telegram_link_tokens', 'users', ['user_id'], ['id'], source_schema='finances', referent_schema='finances', ondelete='CASCADE')
    op.drop_constraint('transactions_account_id_fkey', 'transactions', type_='foreignkey')
    op.drop_constraint('transactions_target_account_id_fkey', 'transactions', type_='foreignkey')
    op.drop_constraint('transactions_category_id_fkey', 'transactions', type_='foreignkey')
    op.drop_constraint('transactions_user_id_fkey', 'transactions', type_='foreignkey')
    op.create_foreign_key(None, 'transactions', 'accounts', ['account_id'], ['id'], referent_schema='finances', ondelete='CASCADE')
    op.create_foreign_key(None, 'transactions', 'categories', ['category_id'], ['id'], referent_schema='finances', ondelete='SET NULL')
    op.create_foreign_key(None, 'transactions', 'users', ['user_id'], ['id'], referent_schema='finances', ondelete='CASCADE')
    op.create_foreign_key(None, 'transactions', 'accounts', ['target_account_id'], ['id'], referent_schema='finances', ondelete='SET NULL')
    op.alter_column('users', 'telegram_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=True)
    op.alter_column('users', 'telegram_username',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'telegram_username',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('users', 'telegram_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.create_foreign_key('transactions_user_id_fkey', 'transactions', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('transactions_category_id_fkey', 'transactions', 'categories', ['category_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('transactions_target_account_id_fkey', 'transactions', 'accounts', ['target_account_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('transactions_account_id_fkey', 'transactions', 'accounts', ['account_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'telegram_link_tokens', schema='finances', type_='foreignkey')
    op.create_foreign_key('telegram_link_tokens_user_id_fkey', 'telegram_link_tokens', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'categories', schema='finances', type_='foreignkey')
    op.create_foreign_key('categories_user_id_fkey', 'categories', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'budgets', schema='finances', type_='foreignkey')
    op.drop_constraint(None, 'budgets', schema='finances', type_='foreignkey')
    op.create_foreign_key('budgets_user_id_fkey', 'budgets', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('budgets_category_id_fkey', 'budgets', 'categories', ['category_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'accounts', schema='finances', type_='foreignkey')
    op.create_foreign_key('accounts_user_id_fkey', 'accounts', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_table('telegram_user_state',
    sa.Column('chat_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('state', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('chat_id', name='telegram_user_state_pkey'),
    schema='bot'
    )
    op.create_table('finance_transactions',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('bot.finance_transactions_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('account_number', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('date_msk', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('time_msk', postgresql.TIME(), autoincrement=False, nullable=False),
    sa.Column('auth_code', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('category', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('amount', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=False),
    sa.Column('tx_type', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('balance', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True),
    sa.Column('date_operation', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('merchant', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('telegram_id', sa.BIGINT(), autoincrement=False, nullable=True, comment='Telegram ID пользователя который загрузил выписку'),
    sa.Column('import_status', sa.VARCHAR(length=20), server_default=sa.text("'pending'::character varying"), autoincrement=False, nullable=False, comment='pending — не обработана, done — импортирована, error — ошибка импорта'),
    sa.Column('imported_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True, comment='Время когда ImportService обработал эту запись'),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='finance_transactions_pkey'),
    sa.UniqueConstraint('account_number', 'date_msk', 'time_msk', 'auth_code', 'amount', name='finance_transactions_unique'),
    schema='bot',
    comment='Сырые транзакции из банковских выписок, загруженных через Telegram бот'
    )
    op.create_index('ix_bot_ft_telegram_id_status', 'finance_transactions', ['telegram_id', 'import_status'], unique=False, schema='bot', postgresql_where="((import_status)::text = 'pending'::text)")
    op.create_index('ix_bot_ft_telegram_id', 'finance_transactions', ['telegram_id'], unique=False, schema='bot')
    op.create_index('ix_bot_ft_import_status', 'finance_transactions', ['import_status'], unique=False, schema='bot', postgresql_where="((import_status)::text = 'pending'::text)")
    op.create_index('ix_bot_ft_date_msk', 'finance_transactions', ['date_msk'], unique=False, schema='bot')
    op.create_table('telegram_upload_log',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('bot.telegram_upload_log_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('chat_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('file_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('mime_type', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('file_size', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('accepted', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('reason', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='telegram_upload_log_pkey'),
    schema='bot'
    )
    # ### end Alembic commands ###
